- hosts: localhost
  connection: local
  vars_prompt:
    - name: "shell_var"
      prompt: "What additional shell do you want install and use (fish/zsh/none)?"
      default: "none"
  
  roles:
    #- ansible-role-customize-gnome
  
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    root_user: root
    dropbox_version: 2020.03.04
    dropbox_machine_map:
      i686: 386
      i386: 386
      x86_64: amd64
      amd64: amd64
    #gnome_user: "{{ root_user }}"
    #gnome_extensions:
    #  - id: 19      # User themes
    #    enable: yes
    #  - id: 3628    # Arc Menu
    #    enable: yes
    #  - id: 5004    # Dash to dock for Cosmic
    #    enable: yes
    #  - id: 517     # Caffeine
    #    enable: yes

  pre_tasks:
    - import_tasks: ./tasks/install_ansible_collections.yml
    
    - name: pre run | retrieve logname
      local_action: command whoami
      register: main_user

    - name: pre run | update & upgrade packages and repositories
      become: yes
      become_user: "{{ root_user }}"
      apt:
        upgrade: yes
        update_cache: yes
        allow_downgrade: yes
      #changed_when: False

  collections:
    - community.general.flatpak

  tasks:    
    - import_tasks: ./tasks/install_setup_packages.yml
    - import_tasks: ./tasks/config_standard_directories.yml

    - import_tasks: ./tasks/install_packages.yml
    - import_tasks: ./tasks/install_flatpaks.yml
    - import_tasks: ./tasks/install_nala.yml
    - import_tasks: ./tasks/install_codium.yml
    - import_tasks: ./tasks/install_terraform.yml 
    - import_tasks: ./tasks/install_dropbox
    - import_tasks: ./tasks/install_chezmoi.yml

    - import_tasks: ./tasks/install_shell_theme.yml
    - import_tasks: ./tasks/install_terminal_theme.yml
    - import_tasks: ./tasks/install_icons.yml
    #- import_tasks: ./tasks/install_gnome_extensions.yml    # let this task commented
    
    - import_tasks: ./tasks/config_conky.yml
    

    - import_tasks: ./tasks/config_shell.yml
    - import tasks: ./tasks/config_terminal.yml
    - import_tasks: ./tasks/config_nautilus.yml

    - import_tasks: ./tasks/copy_autostart.yml



    - include_tasks: ./tasks/install_fish.yml
      when: shell_var == "fish"
    - include_tasks: ./tasks/install_oh_my_zsh.yml
      when: shell_var == "zsh"

  post_tasks:
    - name: post run | Remove ansible_pop_installation directory
      file:
        path: /home/{{ main_user }}/ansible_pop_installation
        state: absent

    - name: post run | cat manual todo list
      command: /bin/cat files/manual_todo_list.md
      register: details

    - name: post run | print todo list
      debug: msg="{{ details.stdout_lines }}"