- name: Pulling Orchis Shell theme repo
  ansible.builtin.git:
    repo: 'https://github.com/vinceliuice/Orchis-theme.git'
    dest: /home/{{ main_user }}/Desktop/Orchis-theme

- name: Correcting source directory core.sh
  replace:
    path: /home/{{ main_user }}/Desktop/Orchis-theme/core.sh
    regexp: '^REPO_DIR.*$' 
    replace: 'REPO_DIR=/home/{{ main_user }}/Desktop/Orchis-theme'

- name: Correcting source directory install.sh
  replace:
    path: /home/{{ main_user }}/Desktop/Orchis-theme/install.sh
    regexp: '^REPO_DIR.*$' 
    replace: 'REPO_DIR=/home/{{ main_user }}/Desktop/Orchis-theme'

- name: Run installation script
  become: yes
  become_user: "{{ main_user }}"
  ansible.builtin.script: /home/{{ main_user }}/Desktop/Orchis-theme/install.sh

- name: Remove shell theme directory
  ansible.builtin.file:
    path: /home/{{ main_user }}/Desktop/Orchis-theme
    state: absent

- name: Set shell theme to Orchis Dark Compact
  dconf:
    key: "/org/gnome/shell/extensions/user-theme/name"
    value: "'Orchis-Dark-Compact'"

- name: Set legacy shell theme to Orchis Dark
  dconf:
    key: "org/gnome/desktop/interface/gtk-theme"
    value: "'Orchis-Dark'"