- name: gnome | shell settings | add maximise & minimal window button
  dconf:
    key: "/org/gnome/desktop/wm/preferences/button-layout"
    value: "'appmenu:minimize,maximize,close'"

- name: gnome | shell settings | show hidden files for gtk
  dconf:
    key: "/org/gtk/settings/file-chooser/show-hidden"
    value: "true"

- name: gnome | shell settings | show hidden files for gtk4
  dconf:
    key: "/org/gtk/gtk4/settings/file-chooser/show-hidden"
    value: "true"

- name: gnome | shell settings | disable hidpi-daemon
  dconf:
    key: "/com/system76/hidpi/enable"
    value: "false"

- name: gnome | shell settings | touchpad area click method
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/click-method"
    value: "'areas'"

- name: gnome | shell settings | show-battery-percentage
  dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "true"

- name: gnome | shell settings | read current icons
  community.general.dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    state: read
  register: gnome_shell_icons

- name: gnome | shell settings | set qogir icon theme
  become_user: "{{ main_user }}"
  dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'Qogir'"
  when: "{{ shell_icons }}" not in gnome_shell_icons and "{{ shell_icons }}" == "Qogir"

- name: gnome | shell settings | read current theme
  community.general.dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    state: read
  register: gnome_shell_theme

- name: gnome | shell settings | set orchis-dark shell theme
  become_user: "{{ main_user }}"
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Orchis-Dark'"
  when: "{{ shell_theme }}" not in gnome_shell_theme and "{{ shell_theme }}" == "Orchis-Dark"