- name: Nautilus Icon View Caption Size extension
  dconf: 
    key: "/org/gnome/nautilus/icon-view/captions"
    value : "['size', 'none', 'none']"

- name: Nautilus preview files
  become: yes
  become_user: "{{ root_user }}"
  ansible.builtin.apt:
    name: gnome-sushi 

- name: Nautilus resize images extension
  become: yes
  become_user: "{{ root_user }}"
  ansible.builtin.apt: 
    name: 
      - imagemagick 
      - nautilus-image-converter

- name: Nautilus open as root extension
  become: yes
  become_user: "{{ root_user }}"
  ansible.builtin.apt: 
    name: nautilus-admin

- name: Message post installation
  debug:
    msg: "Nautilus extensions installed, close all instances with nautilus -q or with GUI and restart it"
