- name: Check if autostart directory exist
  stat:
    path: /home/{{ main_user }}/.config/autostart
  register: directory_autostart

- name: Create autostart directory if it doesn't exist
  file:
    path: /home/{{ main_user }}/.config/autostart
    state: directory
    mode: '775'
  when: not directory_autostart.stat.exists


- name: Check if font directory exist
  stat:
    path: /home/{{ main_user }}/.local/share/fonts
  register: directory_font

- name: Create font directory
  file:
    path: /home/{{ main_user }}/.local/share/fonts
    state: directory
    mode: '775'
  when: not directory_font.stat.exists


- name: Check if icons directory exist
  stat:
    path: /home/{{ main_user }}/.icons
  register: directory_icons

- name: Create .icons directory if it doesn't exist
  file:
    path: /home/{{ main_user }}/.icons
    state: directory
    mode: '775'
  when: not directory_icons.stat.exists


- name: Check if themes directory exist
  stat:
    path: /home/{{ main_user }}/.themes
  register: directory_themes

- name: Create .themes directory if it doesn't exist
  file:
    path: /home/{{ main_user }}/.themes
    state: directory
    mode: '775'


- name: Check if ansible pop installation download directory exist
  stat:
    path: /home/{{ main_user }}/ansible_pop_installation
  register: directory_pop_ansible

- name: Create directory for downloadable executables if it doesn't exist
  file:
    path: /home/{{ main_user }}/ansible_pop_installation
    state: directory
    mode: '775'
  when: not directory_pop_ansible.stat.exists