- name: gnome | terminal | set terminal configuration
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/{{ item.key }}"
    value: "{{ item.value}}"
  with_items:
    - { key: font, value: "'DejaVu Sans Mono 12'" }