- name: directories setup | .autostart | check if directory exist
  stat:
    path: /home/{{ main_user }}/.config/autostart
  register: directory_autostart

- name: directories setup | .autostart | create directory
  file:
    path: /home/{{ main_user }}/.config/autostart
    state: directory
    mode: '775'
  when: not directory_autostart.stat.exists


- name: directories setup | .font | check if directory exist
  stat:
    path: /home/{{ main_user }}/.local/share/fonts
  register: directory_font

- name: directories setup | .font | create directory
  file:
    path: /home/{{ main_user }}/.local/share/fonts
    state: directory
    mode: '775'
  when: not directory_font.stat.exists


- name: directories setup | .icons | check if directory exist
  stat:
    path: /home/{{ main_user }}/.icons
  register: directory_icons

- name: directories setup | .icons | create directory
  file:
    path: /home/{{ main_user }}/.icons
    state: directory
    mode: '775'
  when: not directory_icons.stat.exists


- name: directories setup | .themes | check if directory exist
  stat:
    path: /home/{{ main_user }}/.themes
  register: directory_themes

- name: directories setup | .themes | Create directory
  file:
    path: /home/{{ main_user }}/.themes
    state: directory
    mode: '775'


- name: directories setup | ansible_pop_installation | check if directory exist
  stat:
    path: /home/{{ main_user }}/ansible_pop_installation
  register: directory_pop_ansible

- name: directories setup | ansible_pop_installation | create directory
  file:
    path: /home/{{ main_user }}/ansible_pop_installation
    state: directory
    mode: '775'
  when: not directory_pop_ansible.stat.exists