- name: Install chezmoi
  shell:
    cmd: sh -c "$(curl -fsLS https://chezmoi.io/get)"

- name: Sync chezmoi dotfiles
  shell:
    cmd: /home/{{ main_user }}/bin/chezmoi init --apply https://github.com/DrPulse/dotfiles.git