- name: Add the flathub flatpak repository remote to the user installation
  become: yes
  become_user: "{{ main_user }}"
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install user flatpaks
  become: yes
  become_user: "{{ main_user }}"
  community.general.flatpak:
    name:
      - org.qbittorrent.qBittorrent
      - com.discordapp.Discord
      - fr.romainvigier.MetadataCleaner
      - org.libreoffice.LibreOffice
      - org.onlyoffice.desktopeditors
      - org.kde.krita
      - com.dropbox.Client
    state: present
    method: user
