- name: system setup | packages | install setup system packages
  become_user: "{{ root_user }}"
  package:
    name:
      - dconf-cli
      - lm-sensors
      - python3
      - python3-pip
      - python3-psutil
      - sassc