- name: software | packages | add flathub repository remote
  become: yes
  become_user: "{{ main_user }}"
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: software | packages | flatpak packages installation
  become: yes
  become_user: "{{ main_user }}"
  community.general.flatpak:
    name:
      - org.qbittorrent.qBittorrent
      - com.discordapp.Discord
      - fr.romainvigier.MetadataCleaner
      - org.libreoffice.LibreOffice
      - org.onlyoffice.desktopeditors
      - org.kde.krita
    state: present
    method: user

- name: software | packages | update flatpaks
  become: yes
  become_user: "{{ root_user }}"
  shell: flatpak update --noninteractive
    