- name: software | nala | add source repository 
  become: yes
  become_user: "{{ root_user }}"
  shell: echo "deb-src https://deb.volian.org/volian/ scar main" | tee -a /etc/apt/sources.list.d/volian-archive-scar-unstable.list

- name: software | nala | update apt cache
  become: yes
  become_user: "{{ root_user }}"
  apt: 
    update_cache: yes
  changed_when: False

- name: software | nala | package installation
  become: yes
  become_user: "{{ root_user }}"
  apt:
    name:
      - nala
    state: latest
