- name: software | dropbox | download .deb
  ansible.builtin.command: >
    curl -sSL
    https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_{{ dropbox_version }}_{{ dropbox_machine_map[ansible_machine] }}.deb
    -o /home/{{ main_user }}/ansible_pop_installation/dropbox_{{ dropbox_version }}_{{ dropbox_machine_map[ansible_machine] }}.deb
  args:
    creates: "/home/{{ main_user }}/ansible_pop_installation/dropbox_{{ dropbox_version }}_{{ dropbox_machine_map[ansible_machine] }}.deb"
    warn: false
  
- name: software | dropbox | give executable right to .deb
  file: 
    path: /home/{{ main_user }}/ansible_pop_installation/dropbox_{{ dropbox_version }}_{{ dropbox_machine_map[ansible_machine] }}.deb
    mode: '755  '

- name: software | dropbox | deb file installation
  become: yes
  become_user: "{{ root_user }}"
  ansible.builtin.apt:
    deb: /home/{{ main_user }}/ansible_pop_installation/dropbox_{{ dropbox_version }}_{{ dropbox_machine_map[ansible_machine] }}.deb

- name: software | dropbox | dropbox dependency installation
  become: yes
  become_user: "{{ root_user }}"
  ansible.builtin.apt:
    name: python3-gpg
  
- name: software | dropbox | remove .deb package
  ansible.builtin.file:
    path: /home/{{ main_user }}/ansible_pop_installation/dropbox_{{ dropbox_version }}_{{ dropbox_machine_map[ansible_machine] }}.deb
    state: absent

- name: software | dropbox | post installation message
  debug:
    msg: "Dropbox installed, launch the app and accept the proprietary daemon"