- name: software | chezmoi | package installation
  become: yes
  become_user: "{{ root_user }}"
  shell:
    chdir: /
    cmd: sh -c "$(curl -fsLS https://chezmoi.io/get)"

- name: software | chezmoi | sync dotfiles
  shell: /bin/chezmoi init --apply https://github.com/DrPulse/dotfiles.git