- name: software | vscodium | get url
  get_url:
    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    dest: /home/{{ main_user }}/ansible_pop_installation

- name: software | vscodium | add apt signing key
  become: yes
  become_user: "{{ root_user }}"
  ansible.builtin.apt_key:
    file: /home/{{ main_user }}/ansible_pop_installation/pub.gpg

- name: software | vscodium | add source repository
  become: yes
  become_user: "{{ root_user }}"
  ansible.builtin.apt_repository:
    repo: deb https://download.vscodium.com/debs vscodium main
    update_cache: yes 
    
- name: software | vscodium | remove bgp key
  ansible.builtin.file:
    path: /home/{{ main_user }}/ansible_pop_installation/pub.gpg
    state: absent

- name: software | vscodium | package installation
  become: yes
  become_user: "{{ root_user }}"
  apt:
    name:
      - codium
    state: latest