- name: Install gnome shell extension
  become: yes
  become_user: "{{ root_user }}"
  package:
    name:
      - gnome-shell
      - gnome-shell-extensions

#- name: Enable Gnome Shell extension 
#  command: gnome-extensions enable apps-menu@gnome-shell-extensions.gcampax.github.com

- name: Enable User Theme extension 
  ansible.builtin.shell:
    cmd: gnome-shell-extension-tool -e user-theme@gnome-shell-extensions.gcampax.github.com
           
- name: Pulling ArcMenu repo
  ansible.builtin.git:
    repo: 'https://gitlab.com/arcmenu/ArcMenu.git'
    dest: /home/{{ main_user }}/ansible_pop_installation/ArcMenu

- name: make install ArcMenu
  make:
    chdir: /home/{{ main_user }}/ansible_pop_installation/ArcMenu
    target: install

#- name: Enable ArcMenu extension 
#  command: gnome-extensions enable arcmenu@arcmenub.com

- name: Remove ArcMenu directory
  ansible.builtin.file:
    path: /home/{{ main_user }}/ansible_pop_installation/ArcMenu
    state: absent
