- name: software | nala | check if installed
  command: dpkg-query -l nala
  register: nala_package_check

- name: software | nala | add repository to sources
  become: yes
  become_user: "{{ root_user }}"
  shell: echo "deb https://deb.volian.org/volian/ scar main" | tee /etc/apt/sources.list.d/volian-archive-scar-unstable.list \
  when: nala_package_check is failed

- name: software | nala | add key to trusted repository 
  become: yes
  become_user: "{{ root_user }}"
  shell: wget -qO - https://deb.volian.org/volian/scar.key |  tee /etc/apt/trusted.gpg.d/volian-archive-scar-unstable.gpg > /dev/null
  when: nala_package_check is failed

#- name: software | nala | add source repository 
#  become: yes
#  become_user: "{{ root_user }}"
#  shell:
#    cmd: echo "deb-src https://deb.volian.org/volian/ scar main" | tee -a /etc/apt/sources.list.d/volian-archive-scar-unstable.list

- name: update repositories
  become: yes
  become_user: "{{ root_user }}"
  apt: 
    update_cache: yes
  changed_when: False
  when: nala_package_check is failed

- name: Install nala package
  become: yes
  become_user: "{{ root_user }}"
  package:
    name:
      - nala
    state: latest
  when: nala_package_check is failed