- name: software | codium | check if installed
  command: dpkg-query -l codium
  register: codium_package_check
  failed_when: 'Command "dpkg" not found in codium_package_check.stdout'

- name: software | codium | get url
  get_url:
    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    dest: /home/{{ main_user }}/ansible_pop_installation
  when: codium_package_check is failed

- name: software | codium | add apt signing key
  become: yes
  become_user: "{{ root_user }}"
  ansible.builtin.apt_key:
    file: /home/{{ main_user }}/ansible_pop_installation/pub.gpg
  when: codium_package_check is failed

- name: software | codium | add source repository
  become: yes
  become_user: "{{ root_user }}"
  ansible.builtin.apt_repository:
    repo: deb https://download.vscodium.com/debs vscodium main
    update_cache: yes 
  when: codium_package_check is failed

- name: software | codium | remove bgp key
  ansible.builtin.file:
    path: /home/{{ main_user }}/ansible_pop_installation/pub.gpg
    state: absent
  when: codium_package_check is failed

- name: software | codium | package installation
  become: yes
  become_user: "{{ root_user }}"
  apt:
    name:
      - codium
    state: latest
  when: codium_package_check is failed