- name: Install chezmoi
  shell:
    chdir: /
    cmd: sh -c "$(curl -fsLS https://chezmoi.io/get)"

- name: Sync chezmoi dotfiles
  shell:
    cmd: /bin/chezmoi init --apply https://github.com/DrPulse/dotfiles.git