- name: Download dropbox .deb
  ansible.builtin.command: >
    curl -sSL
    https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_{{ dropbox_version }}_{{ dropbox_machine_map[ansible_machine] }}.deb
    -o /home/{{ main_user }}/ansible_pop_installation/dropbox_{{ dropbox_version }}_{{ dropbox_machine_map[ansible_machine] }}.deb
  args:
    creates: "/home/{{ main_user }}/ansible_pop_installation/dropbox_{{ dropbox_version }}_{{ dropbox_machine_map[ansible_machine] }}.deb"
    warn: false
  
- name: Give executable right
  file: 
    path: /home/{{ main_user }}/ansible_pop_installation/dropbox_{{ dropbox_version }}_{{ dropbox_machine_map[ansible_machine] }}.deb
    mode: '755  '

- name: install deb file
  become: yes
  become_user: "{{ root_user }}"
  ansible.builtin.apt:
    deb: /home/{{ main_user }}/ansible_pop_installation/dropbox_{{ dropbox_version }}_{{ dropbox_machine_map[ansible_machine] }}.deb

- name: Install dropbox dependency
  become: yes
  become_user: "{{ root_user }}"
  ansible.builtin.apt:
    name: python3-gpg
  
- name: Remove .deb package
  ansible.builtin.file:
    path: /home/{{ main_user }}/ansible_pop_installation/dropbox_{{ dropbox_version }}_{{ dropbox_machine_map[ansible_machine] }}.deb
    state: absent

- name: Message post installation
  debug:
    msg: "Dropbox installed, launch the app and accept the proprietary daemon"